<?php

declare(strict_types=1);

namespace Talea\Front;

use Talea\Core\App;
use Talea\Core\Response;

/**
 * Full-page cache for visitors who are not signed in (files in storage/cache/pages, valid for 5 minutes).
 * A page from the cache costs one database query instead of dozens. Any change in the administration clears the cache.
 * Nothing personal is cached: signed-in administration users, previews.
 */
final class Cache
{
    private const string FOLDER = TALEA_ROOT . '/storage/cache/pages';
    private const int LINK_LIFETIME = 300;

    /** Ad and campaign tracking parameters: they do not change the page, so the cache should not be bypassed for them. */
    private const string TRACKING_PARAMS = '/^(utm_[a-z]+|fbclid|gclid|gbraid|wbraid|msclkid|dclid|tl_[a-z]+|_ga|_gl|yclid|igshid|ref)$/';

    /** @var resource|null lock of the page this request is regenerating right now */
    private static $lock = null;

    public static function load(App $app): ?Response
    {
        $file = self::file($app);
        if ($file === null || !is_file($file)) {
            return null;
        }
        if (filemtime($file) < time() - self::LINK_LIFETIME) {
            // An expired page is regenerated by whoever comes first; others arriving in the same second still get the old
            // one (for at most a minute longer). Without this, all hundred visitors would build the same page from the
            // database at once.
            $lock = @fopen($file . '.lock', 'c');
            if ($lock === false || flock($lock, LOCK_EX | LOCK_NB)) {
                self::$lock = $lock ?: null; // held until save() or the end of the request

                return null;
            }
            fclose($lock);
            if (filemtime($file) < time() - self::LINK_LIFETIME - 60) {
                return null;
            }
        }
        [$header, $html] = explode("\n", (string) file_get_contents($file), 2) + [1 => ''];
        $meta = json_decode($header, true);
        if (!is_array($meta) || $html === '') {
            return null;
        }
        Stats::record($app, $meta['news_id'] ?? null);
        if (!empty($meta['news_id'])) {
            $app->db()->run('UPDATE {news} SET visit = visit + 1 WHERE news_id = ?', [(int) $meta['news_id']]);
        }
        // the browser may keep the page and only ask whether it has changed (304 without a body)
        $etag = '"' . substr(md5($file . filemtime($file)), 0, 16) . '"';
        $headers = ['Content-Type' => 'text/html; charset=utf-8', 'X-Cache' => 'talea', 'ETag' => $etag, 'Cache-Control' => 'no-cache'];
        if (trim((string) ($_SERVER['HTTP_IF_NONE_MATCH'] ?? '')) === $etag) {
            return new Response('', 304, $headers);
        }

        return new Response($html, 200, $headers);
    }

    public static function save(App $app, string $html, ?int $idc): void
    {
        $file = self::file($app);
        if ($file === null) {
            return;
        }
        if (!is_dir(self::FOLDER)) {
            @mkdir(self::FOLDER, 0775, true);
        }
        @file_put_contents($file, json_encode(['news_id' => $idc]) . "\n" . $html, LOCK_EX);
        if (self::$lock !== null) {
            flock(self::$lock, LOCK_UN);
            fclose(self::$lock);
            self::$lock = null;
            @unlink($file . '.lock');
        }
        if (random_int(1, 100) === 1) {
            // occasional cleanup: otherwise expired files would disappear only on a change in the administration
            foreach (glob(self::FOLDER . '/*.html') ?: [] as $old) {
                if (filemtime($old) < time() - self::LINK_LIFETIME) {
                    @unlink($old);
                }
            }
        }
    }

    /**
     * Short cache of text outputs that are the same for everyone (RSS, sitemap, feed.json, llms.txt): readers and bots
     * fetch them over and over, and without a cache they are built from the database every time. The key must include
     * everything the output depends on.
     *
     * @param callable(): string $produce
     */
    public static function text(App $app, string $key, callable $produce): string
    {
        if (!$app->settings()->bool('page_cache')) {
            return $produce();
        }
        // the .html extension only because of clear() - any change in the administration deletes these files too
        $file = self::FOLDER . '/source-' . sha1($app->request->basePath() . '|' . $key) . '.html';
        if (is_file($file) && filemtime($file) >= time() - self::LINK_LIFETIME && ($content = file_get_contents($file)) !== false && $content !== '') {
            return $content;
        }
        $content = $produce();
        if (!is_dir(self::FOLDER)) {
            @mkdir(self::FOLDER, 0775, true);
        }
        @file_put_contents($file, $content, LOCK_EX);

        return $content;
    }

    public static function clear(): void
    {
        foreach (array_merge(glob(self::FOLDER . '/*.html') ?: [], glob(self::FOLDER . '/*.lock') ?: []) as $file) {
            @unlink($file);
        }
    }

    /** Cache file for this request, or null when it should not be cached. */
    private static function file(App $app): ?string
    {
        $r = $app->request;
        $s = $app->settings();
        if (!$s->bool('page_cache') || $r->isPost()) {
            return null;
        }
        $params = array_filter(array_keys($_GET), fn (int|string $k): bool => !preg_match(self::TRACKING_PARAMS, (string) $k));
        if (array_diff($params, ['page']) !== []) {
            return null;
        }
        foreach (array_keys($_COOKIE) as $cookie) {
            if ($cookie === 'talea' || $cookie === 'tl_preview') { // signed-in administration user (session), preview of drafts
                return null;
            }
        }

        return self::FOLDER . '/' . md5($r->origin() . '|' . \Talea\Core\Language::code() . '|' . $r->path() . '|' . $r->getInt('page', 1)) . '.html';
    }
}
