<?php
/** Step 1 of the English identifiers (docs/glossary.md): tools and tests. Nothing here is part of a release package. */

return [
    'paths' => ['tools/'],
    'files' => [
        'tools/unit-tests.php' => 'tools/unit-tests.php',
        'tools/release.php' => 'tools/release.php',
        'tools/check-channel.php' => 'tools/check-channel.php',
        'tools/find-czech.php' => 'tools/find-czech.php',
        'tools/add-translations.py' => 'tools/add-translations.py',
        'tools/test-migrations.sh' => 'tools/test-migrations.sh',
        'tools/fixtures/wordpress-sample.xml' => 'tools/fixtures/wordpress-sample.xml',
        'docs/RELEASING.md' => 'docs/RELEASING.md',
    ],
    'names' => [
        // functions of the tools and properties of test doubles
        'over' => 'check',
        'slovniky' => 'dictionaries',
        'slovnikJs' => 'jsDictionary',
        'maDiakritiku' => 'hasDiacritics',
        'ceskaSlova' => 'czechWords',
        'retezce' => 'jsStrings',
        'volani' => 'calls',
        'odpoved' => 'answer',
        'posledni' => 'last',
    ],
    'vars' => [
        // tools/unit-tests.php
        'chyb' => 'errors', 'celkem' => 'total', 'popis' => 'label', 'skutecne' => 'actual', 'ocekavane' => 'expected',
        'tajemstvi' => 'secret', 'prikazy' => 'statements', 'typy' => 'types', 'chybiPreklad' => 'missingTranslation',
        'slovnik' => 'dictionary', 'vzory' => 'patterns', 'preklady' => 'translations', 'chybi' => 'missing', 'vzor' => 'pattern',
        'soubor' => 'file', 'nativniDialogy' => 'nativeDialogs', 'kod' => 'code', 'qrRadky' => 'qrRows', 'qrOtisk' => 'qrHash',
        'obrSlozka' => 'imageFolder', 'obrTmp' => 'imageTmp', 'obrPng' => 'imagePng', 'obrUlozeno' => 'imageSaved', 'obrSrcset' => 'imageSrcset',
        'kontrola' => 'buildCheck', 'mcpZdroj' => 'mcpSource', 'mcpNastroje' => 'mcpTools', 'mcpHlaseni' => 'mcpMessages', 'mcpSeznam' => 'mcpList',
        'ppKde' => 'popupWhere', 'ppVybrane' => 'popupSelected', 'ppObdobi' => 'popupPeriod', 'enSlovnik' => 'enDictionary',
        'nazvyData' => 'dataNames', 'vadneSlovniky' => 'brokenDictionaries', 'klic' => 'key', 'preklad' => 'translation',
        'vnitrni' => 'internal', 'clanekHtml' => 'articleHtml', 'nastaveni' => 'settings', 'falesny' => 'fake', 'telo' => 'body',
        'prelozeno' => 'translated', 'dlouhy' => 'long', 'docasny' => 'temporary', 'platno' => 'canvas', 'kdeVznika' => 'whereCreated',
        'skript' => 'script', 'slozky' => 'folders', 'zdroj' => 'source', 'odkazy' => 'links', 'bezHledani' => 'withoutSearch',
        'atribut' => 'attribute', 'vSablonach' => 'inTemplates', 'slozka' => 'folder', 'par' => 'pair',
        'skProvozni' => 'skPrimary', 'pkProvozni' => 'pkPrimary', 'skZalozni' => 'skBackup', 'pkZalozni' => 'pkBackup',
        'skNovy' => 'skNew', 'pkNovy' => 'pkNew', 'skCizi' => 'skForeign', 'podepis' => 'sign', 'zprava' => 'message',
        'klice' => 'keys', 'nalezene' => 'found', 'karta' => 'card', 'uklid' => 'cleanup', 'smazano' => 'deleted',
        'pkPuvod' => 'pkOrigin', 'pkKlic' => 'pkKey', 'pkPopis' => 'pkDescription', 'pkKlient' => 'pkClient', 'typ' => 'type',
        'vyzva' => 'challenge', 'puvod' => 'origin', 'priznaky' => 'flags', 'pkVyzva' => 'pkChallenge', 'pkUlozeno' => 'pkSaved',
        'pkOdmitne' => 'pkRejects', 'pkCizi' => 'pkForeign', 'pkPrihlas' => 'pkSignIn', 'pocitadlo' => 'counter', 'klient' => 'client',
        'podpis' => 'signature', 'pkZmeneno' => 'pkChanged', 'cile' => 'targets', 'cestyHtml' => 'routesHtml',
        'wpCesta' => 'wpPath', 'wpOdmitne' => 'wpRejects', 'wpHlavicka' => 'wpHeader', 'wpPolozky' => 'wpItems', 'wpStav' => 'wpState',
        'wpHlava' => 'wpHead', 'wpSkodlive' => 'wpMalicious', 'precteno' => 'read', 'odmitnuto' => 'rejected', 'zly' => 'bad',
        'nazev' => 'name', 'ocekavano' => 'expectedResult', 'wpCisti' => 'wpClean', 'wpNebezpecne' => 'wpUnsafe', 'wpUvod' => 'wpIntro',
        'wpStavy' => 'wpStatuses', 'wpObsazene' => 'wpTaken', 'wpStahovani' => 'wpDownload', 'wpZdrojak' => 'wpSourceHtml',
        'stS' => 'buildS', 'stChyby' => 'buildErrors', 'stHtml' => 'buildHtml', 'stSpravce' => 'buildAdmin', 'stEditor' => 'buildEditor',
        'stHluboka' => 'buildDeep', 'stMnoho' => 'buildMany', 'stStylChyby' => 'buildStyleErrors', 'obsazeneAdresy' => 'takenSlugs',
        'stZahozeno' => 'buildDiscarded', 'stKnihovnaChyby' => 'buildLibraryErrors', 'stKlic' => 'buildKey', 'stSekce' => 'buildSection',
        'zh' => 'fromHtml', 'zhTypy' => 'fromHtmlTypes', 'deti' => 'children', 'zh2' => 'fromHtml2',
        'upStavba' => 'editBuild', 'upChyby' => 'editErrors', 'up' => 'edit', 'upChyby2' => 'editErrors2',
        'kmStavba' => 'compactBuild', 'km' => 'compact', 'tlKontext' => 'buttonContext', 'prehled' => 'overview',
        'typySchematu' => 'schemaTypes', 'klicKnihovny' => 'libraryKey', 'knEn' => 'libraryEn', 'knSchema' => 'librarySchema',
        'knEnSlovnik' => 'libraryEnDictionary', 'knTexty' => 'libraryTexts', 'koPole' => 'collectionFields', 'koChyby' => 'collectionErrors',
        'koData' => 'collectionData', 'koHodnoty' => 'collectionValues', 'koStavba' => 'collectionBuild',
        'enJsSlovnik' => 'enJsDictionary', 'enJsKlice' => 'enJsKeys', 'enTexty' => 'enTexts', 'enPole' => 'enFields',
        'vlastnosti' => 'properties', 'webyChyby' => 'siteErrors', 'webySekce' => 'siteSections', 'webKlic' => 'siteKey', 'web' => 'site',
        'sekceStranky' => 'pageSections', 'kontrolaStranky' => 'pageCheck', 'stavba' => 'build', 'nalezy' => 'findings',
        'nadpisy' => 'headings', 'projdi' => 'walk', 'webyKontrola' => 'sitesCheck', 'jazyk' => 'language', 'varianta' => 'variant',
        'zapnuta' => 'enabled', 'nalez' => 'finding', 'kontaktBezFormulare' => 'contactWithoutForm', 'aiTelo' => 'aiBody',
        'aiNastaveni' => 'aiSettings', 'aiFalesny' => 'aiFake', 'aiPrevod' => 'aiConversion', 'aiStavba' => 'aiBuild', 'aiChyba' => 'aiError',
        'aliasyTrid' => 'classAliases', 'nova' => 'newName', 'stara' => 'oldName', 'prejmenovani' => 'renameOutput', 'prejmenovaniKod' => 'renameCode',
        // tools/release.php, tools/check-channel.php, tools/find-czech.php
        'koren' => 'root', 'verze' => 'version', 'volby' => 'options', 'jmeno' => 'name', 'cil' => 'target', 'verejny' => 'publicKeyFile',
        'soubory_klicu' => 'keyFiles', 'soukromy' => 'privateKeyFile', 'idKlice' => 'keyId', 'soubory' => 'files', 'vynechat' => 'exclude',
        'zipSoubor' => 'zipFile', 'otisky' => 'hashes', 'adresa' => 'manifestUrl', 'chyby' => 'errors', 'stahni' => 'download',
        'archiv' => 'archive', 'vBalicku' => 'inPackage', 'ocisti' => 'clean', 'vse' => 'all', 'jazyky' => 'languages', 'slovo' => 'word',
        'radek' => 'line', 'vT' => 'inT', 'cesky' => 'czech', 'vysledek' => 'result', 'dalsi' => 'next', 'konec' => 'end',
        'trida' => 'className', 'surovy' => 'raw', 'cast' => 'part', 'pevne' => 'fixed', 'texty' => 'texts', 'uzel' => 'node',
        'vypsane' => 'printed', 'duvod' => 'reason', 'slova' => 'words',
    ],
];
