<?php
/**
 * Step 4 of the English identifiers (docs/glossary.md): admin URLs. The old names and values live on in
 * system/src/Admin/LegacyUrls.php (old URLs are translated there); this script moves the code to the current ones:
 *   - URL parameters modul= akce= zalozka= (PHP, templates, scripts, tests, docs) -> module= action= tab= with new values
 *   - ->get()/->post() of those parameters and hidden form fields named after them
 *   - action names at Module::url('…') and Module::back(…, '…'), module idents (IDENT, hasModule('…'), $modules['…'])
 *   - admin template folders named after the module idents, settings tab templates named after the tabs
 * Admin action methods (akceUloz -> actionSave) are renamed by tools/rename.php with the map this script writes
 * (tools/rename/4-actions.php). Database columns named modul/akce are left alone.
 *   php tools/rename/4-urls.php [--apply]
 */

declare(strict_types=1);

$root = dirname(__DIR__, 2);
require $root . '/system/src/Admin/LegacyUrls.php';
use Kaleta\Admin\LegacyUrls;

$apply = in_array('--apply', $argv, true);
$params = ['modul' => ['module', LegacyUrls::MODULES], 'akce' => ['action', LegacyUrls::ACTIONS], 'zalozka' => ['tab', LegacyUrls::TABS]];
$map = fn (string $param, string $value): string => $params[$param][1][$value] ?? $value;

$files = [];
foreach (['system', 'image', 'tools', 'docs', 'layout'] as $dir) {
    foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/' . $dir, FilesystemIterator::SKIP_DOTS)) as $f) {
        $rel = substr($f->getPathname(), strlen($root) + 1);
        if ($f->isFile() && preg_match('/\.(php|js|mjs|sh|md)$/', $rel) && !str_starts_with($rel, 'tools/rename/') && $rel !== 'system/src/Admin/LegacyUrls.php'
            && !str_starts_with($rel, 'system/languages/') && !str_starts_with($rel, 'docs/screenshots/')) {
            $files[] = $rel;
        }
    }
}
array_push($files, 'admin.php', 'CLAUDE.md', 'CONTRIBUTING.md');

$counts = [];
$changed = [];
foreach ($files as $rel) {
    $code = (string) file_get_contents($root . '/' . $rel);
    $new = $code;
    // 1) URL parameters: ?modul=stranky&akce=uloz, &amp;zalozka=zalohy, also where the value is built (modul=' . static::IDENT)
    $new = (string) preg_replace_callback('/(?<=[?&;\'"])(modul|akce|zalozka)=([a-z_]*)(?![a-z_])/', function (array $m) use ($params, $map, &$counts): string {
        $counts['url'] = ($counts['url'] ?? 0) + 1;

        return $params[$m[1]][0] . '=' . $map($m[1], $m[2]);
    }, $new);
    // 2) reading them and hidden form fields
    $new = (string) preg_replace_callback('/->(get|post|getInt)\(([\'"])(modul|akce|zalozka)\2/', fn (array $m): string => '->' . $m[1] . '(' . $m[2] . $params[$m[3]][0] . $m[2], $new);
    $new = (string) preg_replace_callback('/name="(modul|akce|zalozka)"(\s+value="([a-z_]+)")?/', fn (array $m): string => 'name="' . $params[$m[1]][0] . '"'
        . (($m[2] ?? '') !== '' ? ' value="' . $map($m[1], $m[3]) . '"' : ''), $new);
    if (str_ends_with($rel, '.php')) {
        // 3) action names at the module helpers
        $new = (string) preg_replace_callback('/(->url\()([\'"])([a-z_]+)\2/', fn (array $m): string => $m[1] . $m[2] . $map('akce', $m[3]) . $m[2], $new);
        $new = (string) preg_replace_callback('/(->back\((?:[^()]|\((?:[^()]|\([^()]*\))*\))*?,\s*)([\'"])([a-z_]+)\2/', fn (array $m): string => $m[1] . $m[2] . $map('akce', $m[3]) . $m[2], $new);
        // 4) module idents
        $new = (string) preg_replace_callback('/(const string IDENT = \')([a-z_]+)\'/', fn (array $m): string => $m[1] . $map('modul', $m[2]) . "'", $new);
        $new = (string) preg_replace_callback('/(hasModule\(|\$(?:modules|moduly)\[|isset\(\$(?:modules|moduly)\[)\'([a-z_]+)\'/', fn (array $m): string => $m[1] . "'" . $map('modul', $m[2]) . "'", $new);
    }
    if ($new !== $code) {
        $changed[$rel] = $new;
    }
}

// template folders and settings tabs
$moves = [];
foreach (LegacyUrls::TABS as $old => $new) { // tabs first, inside the settings folder before it moves
    foreach (['config', 'settings'] as $folder) {
        if (is_file("$root/system/views/admin/$folder/$old.php")) {
            $moves["system/views/admin/$folder/$old.php"] = "system/views/admin/$folder/$new.php";
        }
    }
}
foreach (LegacyUrls::MODULES as $old => $new) {
    if (is_dir("$root/system/views/admin/$old")) {
        $moves["system/views/admin/$old"] = "system/views/admin/$new";
    }
}

// the method map for tools/rename.php: akceUlozText -> actionSaveText
$pascal = fn (string $snake): string => str_replace('_', '', ucwords($snake, '_'));
$names = [];
foreach (LegacyUrls::ACTIONS as $old => $new) {
    $names['akce' . $pascal($old)] = 'action' . $pascal($new);
}
foreach (['edit', 'export', 'import', 'csv', 'token', 'logout', 'oauth'] as $same) {
    $names['akce' . $pascal($same)] = 'action' . $pascal($same);
}
$mapFile = "<?php\n/** Step 4: admin action methods (generated by tools/rename/4-urls.php from Admin\\LegacyUrls::ACTIONS). */\n\nreturn [\n    'names' => [\n";
foreach ($names as $a => $b) {
    $mapFile .= "        '$a' => '$b',\n";
}
$mapFile .= "    ],\n];\n";

echo count($changed) . " files change, " . count($moves) . " templates move, " . ($counts['url'] ?? 0) . " URL parameters\n";
if (!$apply) {
    echo "dry run – add --apply\n";
    exit(0);
}
foreach ($changed as $rel => $code) {
    file_put_contents("$root/$rel", $code);
}
foreach ($moves as $from => $to) {
    exec('cd ' . escapeshellarg($root) . ' && git mv ' . escapeshellarg($from) . ' ' . escapeshellarg($to), $o, $code);
    if ($code !== 0) {
        exit("git mv $from failed\n");
    }
}
file_put_contents("$root/tools/rename/4-actions.php", $mapFile);
echo "applied; now: php tools/rename.php tools/rename/4-actions.php --apply\n";
