<?php

/**
 * Hard fork (issue #5): the builder vocabulary (build JSON keys, element types, content fields, style properties, tokens,
 * stored values), Czech => English. Generated once from Kaleta\\Mcp\\Vocabulary (reviewed there since 1.6) so it survives
 * the removal of that class in phase 1. Keys are the stored Czech names.
 */

return array (
  'color_properties' => 
  array (
    0 => 'barva',
    1 => 'pozadi',
    2 => 'prekryv',
    3 => 'barva_ramecku',
  ),
  'colors' => 
  array (
    'primarni' => 'primary',
    'primarni-jemna' => 'primary-soft',
    'na-primarni' => 'on-primary',
    'sekundarni' => 'secondary',
    'text' => 'text',
    'tlumeny' => 'muted',
    'pozadi' => 'background',
    'plocha' => 'surface',
    'linka' => 'line',
    'bila' => 'white',
    'cerna' => 'black',
  ),
  'condition_values' => 
  array (
    'ano' => 'yes',
    'ne' => 'no',
  ),
  'conditions' => 
  array (
    'prihlaseni' => 'signed_in',
    'od' => 'from',
    'do' => 'to',
    'jazyky' => 'languages',
    'parametr' => 'url_parameter',
  ),
  'content' => 
  array (
    'sirka' => 'width',
    'video' => 'background_video',
    'odkaz' => 'link',
    'text' => 'text',
    'html' => 'html',
    'src' => 'src',
    'alt' => 'alt',
    'popisek' => 'caption',
    'priorita' => 'priority',
    'varianta' => 'variant',
    'nove_okno' => 'new_window',
    'ikona' => 'icon',
    'ikona_vlevo' => 'icon_left',
    'polozky' => 'items',
    'styl' => 'style',
    'autor' => 'author',
    'pozice' => 'position',
    'jedna' => 'single_open',
    'faq' => 'faq_schema',
    'url' => 'url',
    'titulek' => 'title',
    'plakat' => 'poster',
    'tvar' => 'shape',
    'popis' => 'description',
    'fotky' => 'photos',
    'pomer' => 'ratio',
    'karty' => 'tabs',
    'naraz' => 'per_view',
    'adresa' => 'address',
    'priblizeni' => 'zoom',
    'vyska' => 'height',
    'cislo' => 'number',
    'pred' => 'prefix',
    'za' => 'suffix',
    'hodnota' => 'value',
    'cil' => 'target',
    'konec' => 'end_text',
    'nazvy' => 'show_names',
    'napoveda' => 'placeholder',
    'tlacitko' => 'button_text',
    'pocet' => 'count',
    'kategorie' => 'category',
    'obrazky' => 'images',
    'kolekce' => 'collection',
    'razeni' => 'sort',
    'razeni_pole' => 'sort_field',
    'filtr_pole' => 'filter_field',
    'filtr_hodnota' => 'filter_value',
    'bez_aktualni' => 'exclude_current',
    'obdobi' => 'period',
    'obdobi_od' => 'period_start_field',
    'obdobi_do' => 'period_end_field',
    'filtry' => 'filters',
    'kosik' => 'basket_page',
    'mnozstvi' => 'quantity',
    'porovnani' => 'compare',
    'strankovani' => 'pagination',
    'prazdne' => 'empty_text',
    'nazev' => 'name',
    'pole' => 'fields',
    'dekujeme' => 'thank_you',
    'prijemce' => 'recipient',
    'dekovna' => 'thank_you_page',
    'potvrzeni' => 'confirmation',
    'bez_captcha' => 'no_captcha',
    'poslat_soubor' => 'send_file',
    'souhlas' => 'consent',
    'komponenta' => 'component',
    'hodnoty' => 'values',
    'kod' => 'code',
    'menu' => 'menu',
    'novinky' => 'news_link',
    'mobil' => 'phone_menu',
    'mega' => 'mega_menu',
    'zvyrazneni' => 'highlight',
    'jazyky' => 'language_switcher',
    'smer' => 'direction',
    'udaj' => 'detail',
    'pri_rolovani' => 'on_scroll',
    'text_nahore' => 'text_at_top',
    'pole_poloha' => 'location_field',
    'hledani' => 'search_box',
    'nejblizsi' => 'nearest',
    'mapa' => 'show_map',
    'dalsi_kroky' => 'next_steps',
    'odpovime_do' => 'reply_within_hours',
    'odpovida' => 'who_replies',
    'plany' => 'plans',
    'obrazek_pred' => 'before_image',
    'alt_pred' => 'before_alt',
    'popisek_pred' => 'before_label',
    'obrazek_po' => 'after_image',
    'alt_po' => 'after_alt',
    'popisek_po' => 'after_label',
    'delic' => 'divider_position',
    'body' => 'points',
    'udalosti' => 'milestones',
    'min_hvezd' => 'min_stars',
    'souhrn' => 'summary',
    'sluzba' => 'service',
    'osoba' => 'staff_member',
  ),
  'content_by_type' => 
  array (
    'logo' => 
    array (
      'nazev' => 'show_name',
    ),
  ),
  'field_types' => 
  array (
    'text' => 'text',
    'inline' => 'inline_text',
    'html' => 'html',
    'odkaz' => 'link',
    'obrazek' => 'image',
    'prepinac' => 'boolean',
    'vyber' => 'choice',
    'cislo' => 'number',
    'radky' => 'lines',
    'polozky' => 'items',
    'hodnoty' => 'values',
    'kod' => 'code',
    'textarea' => 'long_text',
  ),
  'icons' => 
  array (
    'fajfka' => 'check',
    'fajfka-kruh' => 'check-circle',
    'hvezda' => 'star',
    'srdce' => 'heart',
    'telefon' => 'phone',
    'email' => 'email',
    'misto' => 'place',
    'hodiny' => 'clock',
    'kalendar' => 'calendar',
    'clovek' => 'person',
    'lide' => 'people',
    'dum' => 'home',
    'stit' => 'shield',
    'stit-fajfka' => 'shield-check',
    'blesk' => 'bolt',
    'list' => 'leaf',
    'auto' => 'car',
    'klic' => 'key',
    'naradi' => 'tools',
    'bublina' => 'speech-bubble',
    'svet' => 'globe',
    'zamek' => 'lock',
    'penize' => 'money',
    'graf' => 'chart',
    'rust' => 'growth',
    'darek' => 'gift',
    'fotak' => 'camera',
    'dokument' => 'document',
    'sipka' => 'arrow',
    'plus' => 'plus',
    'info' => 'info',
    'pozor' => 'warning',
    'medaile' => 'medal',
    'kufr' => 'briefcase',
    'salek' => 'cup',
    'cil' => 'target',
    'raketa' => 'rocket',
    'palec' => 'thumbs-up',
    'zarovka' => 'bulb',
    'github' => 'github',
    'rozvrzeni' => 'layout',
    'tokeny' => 'tokens',
    'chat' => 'chat',
    'clanek' => 'article',
    'vrstvy' => 'layers',
    'obrazek' => 'image',
    'odeslat' => 'send',
    'nastaveni' => 'settings',
  ),
  'item_values' => 
  array (
    'typ' => 
    array (
      'text' => 'text',
      'email' => 'email',
      'tel' => 'tel',
      'textarea' => 'textarea',
      'vyber' => 'select',
      'volba' => 'radio',
      'datum' => 'date',
      'cislo' => 'number',
      'soubor' => 'file',
      'kosik' => 'basket',
      'krok' => 'step',
      'odhad' => 'estimate',
      'souhlas' => 'checkbox',
      'zaskrtnuti' => 'checkboxes',
      'skryte' => 'hidden',
    ),
  ),
  'items' => 
  array (
    'otazka' => 'question',
    'odpoved' => 'answer',
    'src' => 'src',
    'alt' => 'alt',
    'nazev' => 'name',
    'obsah' => 'content',
    'hodnota' => 'value',
    'popisek' => 'label',
    'typ' => 'type',
    'povinne' => 'required',
    'moznosti' => 'options',
    'moznosti_volby' => 'choices',
    'moznosti_zaskrtnuti' => 'checkbox_options',
    'cena_za_jednotku' => 'unit_price',
    'zaklad' => 'base_price',
    'mena' => 'currency',
    'kdyz_pole' => 'show_when_field',
    'kdyz_hodnota' => 'show_when_value',
    'cena' => 'price',
    'obdobi' => 'period',
    'popis' => 'description',
    'funkce' => 'features',
    'tlacitko' => 'button_text',
    'odkaz' => 'link',
    'zvyraznit' => 'highlighted',
    'stitek' => 'badge',
    'x' => 'x',
    'y' => 'y',
    'datum' => 'date',
  ),
  'node' => 
  array (
    'typ' => 'type',
    'znacka' => 'tag',
    'obsah' => 'content',
    'styl' => 'style',
    'tridy' => 'classes',
    'kotva' => 'anchor',
    'popis' => 'label',
    'atributy' => 'attributes',
    'podminky' => 'conditions',
    'zamek' => 'locked',
    'deti' => 'children',
  ),
  'radii' => 
  array (
    'plne' => 'full',
  ),
  'states' => 
  array (
    'zaklad' => 'base',
    'tablet' => 'tablet',
    'mobil' => 'mobile',
    'hover' => 'hover',
    'aktivni' => 'active',
    'hover_tablet' => 'hover_tablet',
    'hover_mobil' => 'hover_mobile',
    'aktivni_tablet' => 'active_tablet',
    'aktivni_mobil' => 'active_mobile',
  ),
  'style' => 
  array (
    'zobrazeni' => 'display',
    'smer' => 'direction',
    'zalamovani' => 'wrap',
    'sloupce' => 'columns',
    'radky' => 'rows',
    'oblasti' => 'areas',
    'oblast' => 'area',
    'rozpeti_sloupcu' => 'column_span',
    'rozpeti_radku' => 'row_span',
    'mezera' => 'gap',
    'zarovnani' => 'align_items',
    'rozmisteni' => 'justify_content',
    'vlastni_zarovnani' => 'align_self',
    'poradi' => 'order',
    'rust' => 'flex',
    'sirka' => 'width',
    'max_sirka' => 'max_width',
    'vyska' => 'height',
    'min_vyska' => 'min_height',
    'pomer_stran' => 'aspect_ratio',
    'prizpusobeni' => 'object_fit',
    'na_stred' => 'center',
    'odsazeni_y' => 'padding_y',
    'odsazeni_x' => 'padding_x',
    'okraj_nahore' => 'margin_top',
    'okraj_dole' => 'margin_bottom',
    'okraj_vlevo' => 'margin_left',
    'okraj_vpravo' => 'margin_right',
    'typ_styl' => 'text_style',
    'velikost_pisma' => 'font_size',
    'tloustka_pisma' => 'font_weight',
    'pismo' => 'font',
    'zarovnani_textu' => 'text_align',
    'radkovani' => 'line_height',
    'velka_pismena' => 'text_transform',
    'proklad' => 'letter_spacing',
    'max_radek' => 'line_length',
    'barva' => 'color',
    'pozadi' => 'background',
    'obrazek_pozadi' => 'background_image',
    'prechod' => 'gradient',
    'paralaxa' => 'background_attachment',
    'prekryv' => 'overlay',
    'ramecek' => 'border',
    'barva_ramecku' => 'border_color',
    'linka_nahore' => 'border_top',
    'linka_dole' => 'border_bottom',
    'zaobleni' => 'radius',
    'stin' => 'shadow',
    'pruhlednost' => 'opacity',
    'orez' => 'overflow',
    'pozice' => 'position',
    'odshora' => 'top',
    'zdola' => 'bottom',
    'zleva' => 'left',
    'zprava' => 'right',
    'posun' => 'translate',
    'meritko' => 'scale',
    'otoceni' => 'rotate',
    'plynule' => 'transition',
    'vrstva' => 'z_index',
    'animace' => 'animation',
    'pohyb' => 'scroll_motion',
    'najeti' => 'hover_effect',
  ),
  'style_types' => 
  array (
    'mezera' => 'space',
    'delka' => 'length',
    'barva' => 'color',
    'krok' => 'step',
    'zaobleni' => 'radius',
    'stin' => 'shadow',
    'ramecek' => 'border',
    'vyber' => 'choice',
    'cislo' => 'number',
    'obrazek' => 'image',
    'sloupce' => 'columns',
    'radky' => 'rows',
    'oblasti' => 'areas',
    'oblast' => 'area',
    'text' => 'text',
  ),
  'text_styles' => 
  array (
    'titulek' => 'title',
    'nadpis-sekce' => 'section-heading',
    'podnadpis' => 'subheading',
    'perex' => 'lead',
    'text' => 'body',
    'drobny' => 'small',
    'nadtitulek' => 'eyebrow',
  ),
  'types' => 
  array (
    'sekce' => 'section',
    'kontejner' => 'container',
    'mrizka' => 'grid',
    'nadpis' => 'heading',
    'text' => 'text',
    'obrazek' => 'image',
    'tlacitko' => 'button',
    'seznam' => 'list',
    'citat' => 'testimonial',
    'faq' => 'faq',
    'video' => 'video',
    'oddelovac' => 'divider',
    'ikona' => 'icon',
    'galerie' => 'gallery',
    'zalozky' => 'tabs',
    'karusel' => 'carousel',
    'mapa' => 'map',
    'vlozeni' => 'embed',
    'drobecky' => 'breadcrumbs',
    'pocitadlo' => 'counter',
    'prubeh' => 'progress_bars',
    'hodnoceni' => 'rating',
    'odpocet' => 'countdown',
    'socialni' => 'social_links',
    'hledani' => 'search',
    'novinky' => 'news_list',
    'kolekce' => 'collection_list',
    'do_poptavky' => 'enquiry_button',
    'pobocky' => 'store_locator',
    'formular' => 'form',
    'rezervace' => 'booking',
    'newsletter' => 'newsletter_signup',
    'komponenta' => 'component',
    'html' => 'custom_html',
    'nahoru' => 'back_to_top',
    'logo' => 'logo',
    'navigace' => 'navigation',
    'jazyky' => 'language_switcher',
    'udaje' => 'company_details',
    'obsah' => 'page_content',
    'cenik' => 'pricing_table',
    'pred_po' => 'before_after',
    'hotspoty' => 'hotspots',
    'casova_osa' => 'timeline',
    'recenze_google' => 'google_reviews',
  ),
  'url_parameter' => 
  array (
    'nazev' => 'name',
    'hodnota' => 'value',
  ),
  'values' => 
  array (
    'sirka' => 
    array (
      'obsah' => 'content',
      'uzka' => 'narrow',
      'plna' => 'full',
    ),
    'varianta' => 
    array (
      'primarni' => 'primary',
      'sekundarni' => 'secondary',
      'obrys' => 'outline',
      'odkaz' => 'link',
    ),
    'ikona' => 
    array (
      'fajfka' => 'check',
      'fajfka-kruh' => 'check-circle',
      'hvezda' => 'star',
      'srdce' => 'heart',
      'telefon' => 'phone',
      'email' => 'email',
      'misto' => 'place',
      'hodiny' => 'clock',
      'kalendar' => 'calendar',
      'clovek' => 'person',
      'lide' => 'people',
      'dum' => 'home',
      'stit' => 'shield',
      'stit-fajfka' => 'shield-check',
      'blesk' => 'bolt',
      'list' => 'leaf',
      'auto' => 'car',
      'klic' => 'key',
      'naradi' => 'tools',
      'bublina' => 'speech-bubble',
      'svet' => 'globe',
      'zamek' => 'lock',
      'penize' => 'money',
      'graf' => 'chart',
      'rust' => 'growth',
      'darek' => 'gift',
      'fotak' => 'camera',
      'dokument' => 'document',
      'sipka' => 'arrow',
      'plus' => 'plus',
      'info' => 'info',
      'pozor' => 'warning',
      'medaile' => 'medal',
      'kufr' => 'briefcase',
      'salek' => 'cup',
      'cil' => 'target',
      'raketa' => 'rocket',
      'palec' => 'thumbs-up',
      'zarovka' => 'bulb',
      'github' => 'github',
      'rozvrzeni' => 'layout',
      'tokeny' => 'tokens',
      'chat' => 'chat',
      'clanek' => 'article',
      'vrstvy' => 'layers',
      'obrazek' => 'image',
      'odeslat' => 'send',
      'nastaveni' => 'settings',
    ),
    'styl' => 
    array (
      'odrazky' => 'bullets',
      'fajfky' => 'checks',
      'bez' => 'none',
      'nabidka' => 'dropdown',
      'rada' => 'row',
    ),
    'tvar' => 
    array (
      'kruh' => 'circle',
      'ctverec' => 'square',
    ),
    'razeni' => 
    array (
      'poradi' => 'order',
      'nazev' => 'name',
      'nejnovejsi' => 'newest',
      'pole' => 'field',
      'pole_sestupne' => 'field_descending',
    ),
    'obdobi' => 
    array (
      '' => '',
      'nadchazejici' => 'upcoming',
      'probihajici' => 'current',
      'minule' => 'past',
    ),
    'menu' => 
    array (
      'hlavni' => 'main',
      'paticka' => 'footer',
    ),
    'zvyrazneni' => 
    array (
      'pozadi' => 'background',
      'podtrzeni' => 'underline',
    ),
    'smer' => 
    array (
      'nahoru' => 'up',
      'dolu' => 'down',
    ),
    'pri_rolovani' => 
    array (
      'pruhledna' => 'transparent',
      'zmensit' => 'shrink',
      'pruhledna-zmensit' => 'transparent_shrink',
    ),
    'text_nahore' => 
    array (
      'svetly' => 'light',
      'tmavy' => 'dark',
    ),
    'udaj' => 
    array (
      'adresa' => 'address',
      'telefon' => 'phone',
      'email' => 'email',
      'hodiny' => 'hours',
      'otevreno' => 'open_now',
      'mapa' => 'map',
      'firma' => 'company',
      'tiraz' => 'imprint',
      'copyright' => 'copyright',
      'nazev' => 'name',
      'popis' => 'description',
      'text_paticky' => 'footer_text',
      'site' => 'social',
      'rss' => 'rss',
    ),
  ),
);
