<?php

declare(strict_types=1);

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/** Generated by tools/schema-to-phinx.php from system/sql/schema.sql. */
final class CreateContentTables extends AbstractMigration
{
    public function change(): void
    {
        $prefix = (string) $this->getAdapter()->getOption('table_prefix'); // foreign key names are unique per database

        $this->table('kategorie', ['id' => false, 'primary_key' => ['idt']])
            ->addColumn('idt', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 120, 'null' => false])
            ->addColumn('popis', 'text', ['null' => false])
            ->addColumn('hodnost', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 100, 'comment' => 'order, higher = higher up'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => 'language version; \'\' = the site\'s default language'])
            ->addColumn('preklad_z', 'integer', ['signed' => false, 'null' => true, 'comment' => 'counterpart in the default language (hreflang, language switcher)'])
            ->addIndex(['seo_link'], ['name' => 'uq_topic_seo', 'unique' => true])
            ->create();

        $this->table('novinky', ['id' => false, 'primary_key' => ['idc']])
            ->addColumn('idc', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 160, 'null' => false])
            ->addColumn('titulek', 'string', ['limit' => 255, 'null' => false])
            ->addColumn('uvod', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => 'intro'])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('obrazek', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'featured image'])
            ->addColumn('obrazek_popis', 'string', ['limit' => 300, 'null' => false, 'default' => '', 'comment' => 'caption of the featured image (empty = the caption from the media library)'])
            ->addColumn('obrazek_autor', 'string', ['limit' => 120, 'null' => false, 'default' => '', 'comment' => 'author of the featured image (empty = the author from the media library)'])
            ->addColumn('tema', 'integer', ['signed' => false, 'null' => false, 'comment' => 'category'])
            ->addColumn('autor', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('datum', 'datetime', ['null' => false, 'comment' => 'publish date (also a future one)'])
            ->addColumn('visible', 'boolean', ['null' => false, 'default' => 0, 'comment' => 'published news item (otherwise a draft)'])
            ->addColumn('t_slova', 'string', ['limit' => 500, 'null' => false, 'default' => '', 'comment' => 'keywords'])
            ->addColumn('seo_titulek', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'custom <title>, empty = the title'])
            ->addColumn('seo_popis', 'string', ['limit' => 320, 'null' => false, 'default' => '', 'comment' => 'custom meta description, empty = from the intro'])
            ->addColumn('noindex', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('faq', 'text', ['null' => true, 'comment' => 'questions and answers: question, the answer below it, an empty line'])
            ->addColumn('visit', 'integer', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'view count'])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addColumn('aktualizovano', 'datetime', ['null' => true, 'comment' => 'when the published news item was substantially updated'])
            ->addColumn('oznameno', 'datetime', ['null' => true, 'comment' => 'when the system announced the publishing (webhook, IndexNow); NULL = not yet'])
            ->addColumn('valid_until', 'date', ['null' => true, 'comment' => 'true until: the day after, the news item hides itself (2.10, Core\\Validity)'])
            ->addColumn('review_by', 'date', ['null' => true, 'comment' => 'review by: on this day the site audit asks for a check (2.10)'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => 'taken from the category on save'])
            ->addColumn('preklad_z', 'integer', ['signed' => false, 'null' => true, 'comment' => 'idc of the news item this one is a translation of'])
            ->addColumn('hledani', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true, 'comment' => 'text without diacritics for search (Core\\Search)'])
            ->addColumn('odkazy_cas', 'datetime', ['null' => true, 'comment' => 'when the links were last checked'])
            ->addColumn('smazano', 'datetime', ['null' => true, 'comment' => 'in the trash since (deleted permanently after 30 days); NULL = not in the trash'])
            ->addIndex(['seo_link'], ['name' => 'uq_clanky_seo', 'unique' => true])
            ->addIndex(['jazyk', 'visible', 'datum'], ['name' => 'ix_clanky_jazyk'])
            ->addIndex(['oznameno', 'visible', 'datum'], ['name' => 'ix_clanky_oznameno'])
            ->addIndex(['datum'], ['name' => 'ix_clanky_datum'])
            ->addIndex(['smazano'], ['name' => 'ix_clanky_smazano'])
            ->addIndex(['tema', 'visible', 'datum'], ['name' => 'ix_clanky_tema'])
            ->addIndex(['autor'], ['name' => 'ix_clanky_autor'])
            ->addIndex(['titulek', 'uvod', 'text', 't_slova'], ['name' => 'ft_clanky', 'type' => 'fulltext'])
            ->addIndex(['hledani'], ['name' => 'ft_clanky_hledani', 'type' => 'fulltext'])
            ->addForeignKey('tema', 'kategorie', 'idt', ['constraint' => $prefix . 'fk_clanky_tema'])
            ->addForeignKey('autor', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_clanky_autor', 'delete' => 'SET_NULL'])
            ->create();

        $this->table('stitky', ['id' => false, 'primary_key' => ['ids']])
            ->addColumn('ids', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 80, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('popis', 'text', ['null' => true, 'comment' => 'intro of the topic page (HTML from the editors)'])
            ->addColumn('obrazek', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addIndex(['seo_link'], ['name' => 'uq_stitky_seo', 'unique' => true])
            ->create();

        $this->table('novinky_stitky', ['id' => false, 'primary_key' => ['idc', 'ids']])
            ->addColumn('idc', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('ids', 'integer', ['signed' => false, 'null' => false])
            ->addIndex(['ids'], ['name' => 'ix_clanky_stitky_stitek'])
            ->addForeignKey('idc', 'novinky', 'idc', ['constraint' => $prefix . 'fk_cs_clanek', 'delete' => 'CASCADE'])
            ->addForeignKey('ids', 'stitky', 'ids', ['constraint' => $prefix . 'fk_cs_stitek', 'delete' => 'CASCADE'])
            ->create();

        $this->table('novinky_revize', ['id' => false, 'primary_key' => ['idr']])
            ->addColumn('idr', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idc', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('kdo', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('titulek', 'string', ['limit' => 255, 'null' => false])
            ->addColumn('uvod', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addIndex(['idc', 'datum'], ['name' => 'ix_revize_clanek'])
            ->addForeignKey('idc', 'novinky', 'idc', ['constraint' => $prefix . 'fk_revize_clanek', 'delete' => 'CASCADE'])
            ->addForeignKey('kdo', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_revize_kdo', 'delete' => 'SET_NULL'])
            ->create();

        $this->table('novinky_koncepty', ['id' => false, 'primary_key' => ['kdo', 'idc']])
            ->addColumn('kdo', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('idc', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('cas', 'datetime', ['null' => false])
            ->addColumn('data', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => 'JSON {form field name: value}'])
            ->create();

        $this->table('stranky', ['id' => false, 'primary_key' => ['ids']])
            ->addColumn('ids', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 120, 'null' => false])
            ->addColumn('titulek', 'string', ['limit' => 200, 'null' => false])
            ->addColumn('popis', 'string', ['limit' => 300, 'null' => false, 'default' => '', 'comment' => 'meta description'])
            ->addColumn('seo_titulek', 'string', ['limit' => 200, 'null' => false, 'default' => '', 'comment' => 'custom <title>, empty = the title'])
            ->addColumn('obrazek', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'image for sharing (og:image), empty = the default from Settings'])
            ->addColumn('noindex', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('heslo_hash', 'string', ['limit' => 255, 'null' => true, 'comment' => 'password-protected page (2.14, Core\\PageLock): password_hash(); NULL = public'])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('zobrazit', 'boolean', ['null' => false, 'default' => 1])
            ->addColumn('zverejnit_od', 'datetime', ['null' => true, 'comment' => 'a hidden page publishes itself at this moment'])
            ->addColumn('valid_until', 'date', ['null' => true, 'comment' => 'true until: the day after, the page hides itself (2.10, Core\\Validity)'])
            ->addColumn('review_by', 'date', ['null' => true, 'comment' => 'review by: on this day the site audit asks for a check (2.10)'])
            ->addColumn('kod_hlavicky', 'text', ['null' => true, 'comment' => 'code for <head> of this page only (administrators, 2.3)'])
            ->addColumn('v_menu', 'boolean', ['null' => false, 'default' => 1, 'comment' => 'link in the site footer / navigation'])
            ->addColumn('poradi', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 100])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addColumn('links_checked', 'datetime', ['null' => true, 'comment' => 'when the links of the published page were last checked (2.14, Core\\Links)'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => 'language version; \'\' = the site\'s default language'])
            ->addColumn('preklad_z', 'integer', ['signed' => false, 'null' => true, 'comment' => 'counterpart in the default language (hreflang, language switcher)'])
            ->addColumn('nadrazena', 'integer', ['signed' => false, 'null' => true, 'comment' => 'parent page: the URL is /nadrazena/stranka'])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true, 'comment' => 'published build (JSON tree of builder elements); NULL = text page'])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true, 'comment' => 'work-in-progress build from the editor; NULL = no unsaved changes'])
            ->addColumn('smazano', 'datetime', ['null' => true, 'comment' => 'in the trash since (deleted permanently after 30 days); NULL = not in the trash'])
            ->addIndex(['seo_link'], ['name' => 'uq_stranky_seo', 'unique' => true])
            ->addIndex(['smazano'], ['name' => 'ix_stranky_smazano'])
            ->addIndex(['zverejnit_od'], ['name' => 'ix_stranky_zverejnit'])
            ->create();

        $this->table('stranky_revize', ['id' => false, 'primary_key' => ['idr']])
            ->addColumn('idr', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('ids', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('kdo', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('titulek', 'string', ['limit' => 200, 'null' => false])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addIndex(['ids', 'idr'], ['name' => 'ix_stranky_revize'])
            ->addForeignKey('ids', 'stranky', 'ids', ['constraint' => $prefix . 'fk_stranky_revize_stranka', 'delete' => 'CASCADE'])
            ->addForeignKey('kdo', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_stranky_revize_kdo', 'delete' => 'SET_NULL'])
            ->create();

        $this->table('casti', ['id' => false, 'primary_key' => ['typ', 'jazyk', 'varianta']])
            ->addColumn('typ', 'string', ['limit' => 20, 'null' => false])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => ''])
            ->addColumn('varianta', 'string', ['limit' => 40, 'null' => false, 'default' => '', 'comment' => '\'\' = default; otherwise the variant for the pages in the stranky list (JSON of numbers)'])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false, 'default' => ''])
            ->addColumn('stranky', 'text', ['null' => true])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->create();

        $this->table('menu', ['id' => false, 'primary_key' => ['umisteni', 'jazyk']])
            ->addColumn('umisteni', 'string', ['limit' => 20, 'null' => false, 'comment' => 'hlavni | paticka'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => '\'\' = the site\'s default language'])
            ->addColumn('polozky', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => 'JSON [{typ: stranka|odkaz|novinky|skupina, ids, url, text, nove_okno, deti: […]}]'])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->create();

        $this->table('presmerovani', ['id' => false, 'primary_key' => ['idp']])
            ->addColumn('idp', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('z_adresy', 'string', ['limit' => 255, 'null' => false, 'comment' => 'path on the site without the leading slash: clanek/stara-adresa'])
            ->addColumn('na_adresu', 'string', ['limit' => 255, 'null' => false, 'comment' => 'path on the site, or a full URL https://...'])
            ->addColumn('typ', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 301, 'comment' => '301 permanent, 302 temporary'])
            ->addColumn('auto_score', 'tinyinteger', ['signed' => false, 'null' => true, 'comment' => 'NULL = by hand or a slug change; 0–100 = created by the daily job with this confidence (2.14, Core\\RedirectMatcher)'])
            ->addColumn('pocet', 'integer', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'how many times the redirect was used'])
            ->addColumn('vytvoreno', 'datetime', ['null' => false])
            ->addIndex(['z_adresy'], ['name' => 'uq_presmerovani', 'unique' => true])
            ->create();

        $this->table('nenalezeno', ['id' => false, 'primary_key' => ['cesta']])
            ->addColumn('cesta', 'string', ['limit' => 255, 'null' => false])
            ->addColumn('pocet', 'integer', ['signed' => false, 'null' => false, 'default' => 1])
            ->addColumn('naposledy', 'datetime', ['null' => false])
            ->addColumn('ignorovano', 'datetime', ['null' => true, 'comment' => 'ignored by the administrator (1.9): out of the warning and the list'])
            ->create();

        $this->table('odkazy_vadne', ['id' => false, 'primary_key' => ['ido']])
            ->addColumn('ido', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('kind', 'string', ['limit' => 10, 'null' => false, 'default' => 'news', 'comment' => 'news | page | item (2.14): what idc is the id of'])
            ->addColumn('idc', 'integer', ['signed' => false, 'null' => false, 'comment' => 'ka_novinky.idc, ka_stranky.ids or ka_kolekce_polozky.idp by kind'])
            ->addColumn('url', 'string', ['limit' => 500, 'null' => false])
            ->addColumn('element', 'string', ['limit' => 40, 'null' => false, 'default' => '', 'comment' => 'the builder element the link is in (page builds), otherwise empty'])
            ->addColumn('stav', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'response code; 0 = the server did not respond, 404 for an own article = does not exist'])
            ->addColumn('cas', 'datetime', ['null' => false])
            ->addIndex(['idc'], ['name' => 'ix_odkazy_clanek'])
            ->create();

        $this->table('import_mapa', ['id' => false, 'primary_key' => ['zdroj', 'typ', 'cizi_id']])
            ->addColumn('zdroj', 'string', ['limit' => 40, 'null' => false, 'comment' => 'where the record comes from: wp:<domain of the old site>'])
            ->addColumn('typ', 'string', ['limit' => 20, 'null' => false, 'comment' => 'clanek | stranka | rubrika | stitek | obrazek | komentar'])
            ->addColumn('cizi_id', 'string', ['limit' => 190, 'null' => false, 'comment' => 'identifier in the source (post number, category URL, hash of the image URL)'])
            ->addColumn('nase_id', 'integer', ['signed' => false, 'null' => false, 'comment' => 'the number of our record; 0 for an image = the download failed'])
            ->addIndex(['zdroj', 'typ', 'nase_id'], ['name' => 'ix_import_mapa_nase'])
            ->create();

        $this->table('notebook', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('topic', 'string', ['limit' => 60, 'null' => false, 'default' => 'other', 'comment' => 'decisions | style | credits | history | todo | other'])
            ->addColumn('title', 'string', ['limit' => 150, 'null' => false])
            ->addColumn('text', 'text', ['null' => false, 'comment' => 'plain text'])
            ->addColumn('pinned', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('author', 'string', ['limit' => 100, 'null' => false, 'default' => '', 'comment' => 'the user\'s name, or the name of the Claude connection'])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('updated_at', 'datetime', ['null' => false])
            ->addIndex(['topic', 'pinned', 'updated_at'], ['name' => 'ix_notebook_topic'])
            ->create();

        $this->table('draft_comments', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('target', 'string', ['limit' => 80, 'null' => false, 'comment' => 'the draft the comment is about, as Core\\Preview signs it: \'stranka:12\''])
            ->addColumn('element', 'string', ['limit' => 40, 'null' => true, 'comment' => 'builder element id the comment points at; NULL = the page as a whole'])
            ->addColumn('quote', 'string', ['limit' => 300, 'null' => false, 'default' => '', 'comment' => 'the text the visitor had selected when writing'])
            ->addColumn('name', 'string', ['limit' => 80, 'null' => false])
            ->addColumn('text', 'text', ['null' => false, 'comment' => 'plain text'])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('resolved_at', 'datetime', ['null' => true])
            ->addColumn('resolved_by', 'integer', ['signed' => false, 'null' => true])
            ->addIndex(['target', 'resolved_at'], ['name' => 'ix_draft_comments_target'])
            ->addIndex(['resolved_by'], ['name' => 'ix_draft_comments_resolved_by'])
            ->addForeignKey('resolved_by', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_draft_comments_resolved_by', 'delete' => 'SET_NULL'])
            ->create();

    }
}
