<?php

declare(strict_types=1);

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/** Generated by tools/schema-to-phinx.php from system/sql/schema.sql. */
final class CreateFormsTables extends AbstractMigration
{
    public function change(): void
    {
        $prefix = (string) $this->getAdapter()->getOption('table_prefix'); // foreign key names are unique per database

        $this->table('poptavky', ['id' => false, 'primary_key' => ['idp']])
            ->addColumn('idp', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('formular', 'string', ['limit' => 120, 'null' => false, 'default' => ''])
            ->addColumn('zdroj', 'string', ['limit' => 40, 'null' => false, 'default' => ''])
            ->addColumn('prvek', 'string', ['limit' => 16, 'null' => false, 'default' => ''])
            ->addColumn('stranka', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addColumn('tema', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'what it was about (2.12, Front\\EnquiryTopic): "<collection> – <item>", the page title or the pop-up name'])
            ->addColumn('vstup', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'the first page of the visit (2.3; only with consent to marketing)'])
            ->addColumn('odkud', 'string', ['limit' => 100, 'null' => false, 'default' => '', 'comment' => 'the site that sent the visitor (2.3; likewise)'])
            ->addColumn('kampan', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'utm_* parameters of the page with the form (or of the visit, 2.3)'])
            ->addColumn('email', 'string', ['limit' => 190, 'null' => false, 'default' => ''])
            ->addColumn('data', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('stav', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('kategorie', 'string', ['limit' => 12, 'null' => false, 'default' => '', 'comment' => 'triage (2.12, Core\\Triage): sales | support | job | supplier | spam | other; \'\' = not sorted yet'])
            ->addColumn('priorita', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => '0 = not set, 1 low, 2 normal, 3 high'])
            ->addColumn('navrh_odpovedi', 'text', ['null' => true, 'comment' => 'a drafted reply (never sent by itself)'])
            ->addColumn('triaged_by', 'string', ['limit' => 40, 'null' => false, 'default' => '', 'comment' => 'claude | assistant | rule | the user\'s name'])
            ->addColumn('triaged_at', 'datetime', ['null' => true])
            ->addColumn('poznamka', 'text', ['null' => true, 'comment' => 'internal note (the visitor does not see it)'])
            ->addColumn('prirazeno', 'integer', ['signed' => false, 'null' => true, 'comment' => 'which user handles the enquiry'])
            ->addColumn('anonymizovano', 'datetime', ['null' => true, 'comment' => 'the person\'s data was blanked at this time (2.14, Core\\Privacy); NULL = still held'])
            ->addIndex(['stav', 'idp'], ['name' => 'ix_poptavky_stav'])
            ->addIndex(['kategorie', 'idp'], ['name' => 'ix_poptavky_kategorie'])
            ->create();

        $this->table('souhlasy', ['id' => false, 'primary_key' => ['ids']])
            ->addColumn('ids', 'biginteger', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('id_souhlasu', 'char', ['limit' => 32, 'null' => false, 'comment' => 'a random identifier stored in the visitor\'s cookie'])
            ->addColumn('cas', 'datetime', ['null' => false])
            ->addColumn('kategorie', 'string', ['limit' => 60, 'null' => false, 'comment' => '"analytika,marketing" or "nic"'])
            ->addIndex(['cas'], ['name' => 'ix_souhlasy_cas'])
            ->addIndex(['id_souhlasu'], ['name' => 'ix_souhlasy_id'])
            ->create();

        $this->table('odberatele', ['id' => false, 'primary_key' => ['ido']])
            ->addColumn('ido', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('email', 'string', ['limit' => 190, 'null' => false])
            ->addColumn('stav', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => '0 awaiting confirmation, 1 confirmed'])
            ->addColumn('token', 'char', ['limit' => 32, 'null' => false, 'comment' => 'confirming and unsubscribing via a link'])
            ->addColumn('zdroj', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'the page they subscribed from'])
            ->addColumn('kampan', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'utm_* of the page or of the visit (2.3)'])
            ->addColumn('vstup', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'the first page of the visit (2.3; only with consent to marketing)'])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('potvrzeno', 'datetime', ['null' => true])
            ->addColumn('sync', 'string', ['limit' => 10, 'null' => false, 'default' => '', 'comment' => 'mailing service: \'\' nothing, ceka, ok, chyba'])
            ->addColumn('sync_chyba', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addIndex(['email'], ['name' => 'uq_odberatel_email', 'unique' => true])
            ->addIndex(['token'], ['name' => 'uq_odberatel_token', 'unique' => true])
            ->create();

        $this->table('odber_fronta', ['id' => false, 'primary_key' => ['idf']])
            ->addColumn('idf', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('email', 'string', ['limit' => 190, 'null' => false])
            ->addColumn('akce', 'string', ['limit' => 10, 'null' => false, 'comment' => 'pridat | odebrat'])
            ->addColumn('pokusy', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('dalsi', 'datetime', ['null' => true, 'comment' => 'next attempt; NULL = given up (visible in Subscribers)'])
            ->addColumn('chyba', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addColumn('vytvoreno', 'datetime', ['null' => false])
            ->addIndex(['dalsi'], ['name' => 'ix_odber_fronta_dalsi'])
            ->create();

        $this->table('newsletters', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('subject', 'string', ['limit' => 200, 'null' => false])
            ->addColumn('preheader', 'string', ['limit' => 200, 'null' => false, 'default' => '', 'comment' => 'preview text shown next to the subject in the inbox'])
            ->addColumn('intro', 'text', ['null' => false])
            ->addColumn('news_mode', 'string', ['limit' => 10, 'null' => false, 'default' => 'latest', 'comment' => 'latest | chosen | none'])
            ->addColumn('news_count', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 3, 'comment' => 'how many of the latest news items'])
            ->addColumn('news_ids', 'string', ['limit' => 500, 'null' => false, 'default' => '', 'comment' => 'chosen news items (idc, comma separated)'])
            ->addColumn('button_label', 'string', ['limit' => 80, 'null' => false, 'default' => ''])
            ->addColumn('button_url', 'string', ['limit' => 500, 'null' => false, 'default' => ''])
            ->addColumn('language', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => 'language of the fixed texts and the news items (empty = the site language)'])
            ->addColumn('status', 'string', ['limit' => 10, 'null' => false, 'default' => 'draft', 'comment' => 'draft | scheduled | sending | sent'])
            ->addColumn('scheduled_at', 'datetime', ['null' => true])
            ->addColumn('html', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true, 'comment' => 'the rendered e-mail, kept from the start of sending'])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('recipients', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('sent_count', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('failed_count', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('author', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('created', 'datetime', ['null' => false])
            ->addColumn('changed', 'datetime', ['null' => true])
            ->addColumn('started_at', 'datetime', ['null' => true])
            ->addColumn('finished_at', 'datetime', ['null' => true])
            ->addIndex(['status', 'scheduled_at'], ['name' => 'ix_newsletters_status'])
            ->create();

        $this->table('newsletter_queue', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('newsletter_id', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('subscriber_id', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('attempts', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('next_attempt', 'datetime', ['null' => true, 'comment' => 'NULL = done (sent or given up)'])
            ->addColumn('sent_at', 'datetime', ['null' => true])
            ->addColumn('error', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addIndex(['newsletter_id', 'subscriber_id'], ['name' => 'ux_newsletter_queue', 'unique' => true])
            ->addIndex(['next_attempt'], ['name' => 'ix_newsletter_queue_next'])
            ->addIndex(['sent_at'], ['name' => 'ix_newsletter_queue_sent'])
            ->create();

        $this->table('testimonial_requests', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idp', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('token_hash', 'char', ['limit' => 64, 'null' => false])
            ->addColumn('email', 'string', ['limit' => 190, 'null' => false, 'default' => ''])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('expires_at', 'datetime', ['null' => false])
            ->addColumn('used_at', 'datetime', ['null' => true])
            ->addColumn('item_id', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('consent', 'text', ['null' => true])
            ->addIndex(['token_hash'], ['name' => 'ux_testimonial_token', 'unique' => true])
            ->addIndex(['idp'], ['name' => 'ix_testimonial_enquiry'])
            ->create();

        $this->table('requests', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('updated_at', 'datetime', ['null' => false])
            ->addColumn('author_id', 'integer', ['signed' => false, 'null' => false, 'comment' => 'ka_uzivatele.idu of the staff member who wrote it'])
            ->addColumn('title', 'string', ['limit' => 190, 'null' => false])
            ->addColumn('text', 'text', ['null' => false])
            ->addColumn('about', 'string', ['limit' => 500, 'null' => false, 'default' => '', 'comment' => 'what it is about: page:<ids> | news:<idc> | item:<idp> | a URL | \'\''])
            ->addColumn('attachments', 'string', ['limit' => 255, 'null' => false, 'default' => '[]', 'comment' => 'JSON list of ka_media.ido (up to 5)'])
            ->addColumn('status', 'string', ['limit' => 12, 'null' => false, 'default' => 'new', 'comment' => 'new | in_progress | done | declined'])
            ->addColumn('done_at', 'datetime', ['null' => true, 'comment' => 'when it was marked done or declined'])
            ->addIndex(['status', 'id'], ['name' => 'ix_requests_status'])
            ->create();

        $this->table('request_messages', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('request_id', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('sender', 'string', ['limit' => 10, 'null' => false, 'comment' => 'claude | person'])
            ->addColumn('sender_name', 'string', ['limit' => 190, 'null' => false, 'default' => '', 'comment' => 'the person\'s name, or the name of the Claude connection'])
            ->addColumn('text', 'text', ['null' => false])
            ->addColumn('links', 'text', ['null' => true, 'comment' => 'JSON list of {"label": …, "url": …} – the drafts Claude made'])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addIndex(['request_id', 'id'], ['name' => 'ix_request_messages'])
            ->addForeignKey('request_id', 'requests', 'id', ['constraint' => $prefix . 'fk_request_messages', 'delete' => 'CASCADE'])
            ->create();

        $this->table('whistleblowing_cases', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('number', 'string', ['limit' => 12, 'null' => false, 'comment' => 'the case number the reporter knows: "2026-0007"'])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('status', 'string', ['limit' => 12, 'null' => false, 'default' => 'received', 'comment' => 'received | acknowledged | in_progress | closed'])
            ->addColumn('acknowledged_at', 'datetime', ['null' => true, 'comment' => 'acknowledgement of receipt (due within 7 days)'])
            ->addColumn('feedback_due', 'datetime', ['null' => false, 'comment' => 'created_at + 3 months'])
            ->addColumn('closed_at', 'datetime', ['null' => true, 'comment' => 'closed cases are deleted after the retention period'])
            ->addColumn('flood', 'boolean', ['null' => false, 'default' => 0, 'comment' => 'received when 20 or more came in the hour before (3.3.3)'])
            ->addColumn('text', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => 'encrypted'])
            ->addColumn('contact', 'text', ['null' => true, 'comment' => 'encrypted: name and contact, NULL = anonymous'])
            ->addColumn('attachments', 'text', ['null' => true, 'comment' => 'encrypted JSON: [{name, path, size}], files in storage/oznameni/'])
            ->addColumn('code_hash', 'char', ['limit' => 64, 'null' => false, 'comment' => 'sha256 of the case number and the access code'])
            ->addIndex(['number'], ['name' => 'ux_whistleblowing_number', 'unique' => true])
            ->addIndex(['status', 'closed_at'], ['name' => 'ix_whistleblowing_status'])
            ->create();

        $this->table('whistleblowing_messages', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('case_id', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('sender', 'string', ['limit' => 10, 'null' => false, 'comment' => 'reporter | handler'])
            ->addColumn('text', 'text', ['null' => false, 'comment' => 'encrypted'])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addIndex(['case_id', 'id'], ['name' => 'ix_whistleblowing_messages_case'])
            ->create();

    }
}
