<?php

declare(strict_types=1);

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/** Generated by tools/schema-to-phinx.php from system/sql/schema.sql. */
final class CreateBuilderTables extends AbstractMigration
{
    public function change(): void
    {
        $prefix = (string) $this->getAdapter()->getOption('table_prefix'); // foreign key names are unique per database

        $this->table('stavba_revize', ['id' => false, 'primary_key' => ['idr']])
            ->addColumn('idr', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('ids', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('cast', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('kdo', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addIndex(['ids', 'idr'], ['name' => 'ix_stavba_revize'])
            ->addIndex(['cast', 'idr'], ['name' => 'ix_stavba_revize_cast'])
            ->addForeignKey('ids', 'stranky', 'ids', ['constraint' => $prefix . 'fk_stavba_revize_stranka', 'delete' => 'CASCADE'])
            ->addForeignKey('kdo', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_stavba_revize_kdo', 'delete' => 'SET_NULL'])
            ->create();

        $this->table('tridy', ['id' => false, 'primary_key' => ['nazev']])
            ->addColumn('nazev', 'string', ['limit' => 60, 'null' => false, 'comment' => 'class name in HTML (lowercase letters, digits, hyphens, __)'])
            ->addColumn('styl', 'text', ['null' => false, 'comment' => '{"zaklad": {...}, "tablet": {...}, "mobil": {...}, "hover": {...}}'])
            ->addColumn('css', 'text', ['null' => true, 'comment' => 'custom declarations (only safe ones, see Builder\\Style::customCss)'])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->create();

        $this->table('sekce', ['id' => false, 'primary_key' => ['idx']])
            ->addColumn('idx', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('prvek', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => 'JSON of one element (usually a section) including its contents'])
            ->addColumn('kit_key', 'string', ['limit' => 80, 'null' => true, 'comment' => 'the key it came with from a fleet design kit (2.16, Fleet\\Kit): the next kit updates it'])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->create();

        $this->table('komponenty', ['id' => false, 'primary_key' => ['idm']])
            ->addColumn('idm', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('vlastnosti', 'text', ['null' => false])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('kit_key', 'string', ['limit' => 80, 'null' => true, 'comment' => 'the key it came with from a fleet design kit (2.16, Fleet\\Kit): the next kit updates its draft'])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->create();

        $this->table('popupy', ['id' => false, 'primary_key' => ['idpp']])
            ->addColumn('idpp', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('adresa', 'string', ['limit' => 60, 'null' => false])
            ->addColumn('typ', 'string', ['limit' => 20, 'null' => false, 'default' => 'okno'])
            ->addColumn('spoustec', 'string', ['limit' => 20, 'null' => false, 'default' => 'cas'])
            ->addColumn('hodnota', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 5])
            ->addColumn('pravidla', 'text', ['null' => false])
            ->addColumn('cetnost', 'string', ['limit' => 20, 'null' => false, 'default' => 'relace'])
            ->addColumn('dni', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 7])
            ->addColumn('aktivni', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('valid_until', 'date', ['null' => true, 'comment' => 'true until: the day after, the pop-up switches itself off (2.10, Core\\Validity)'])
            ->addColumn('review_by', 'date', ['null' => true, 'comment' => 'review by: on this day the site audit asks for a check (2.10)'])
            ->addColumn('poradi', 'smallinteger', ['signed' => true, 'null' => false, 'default' => 100])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('zobrazeni', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('zavreni', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('konverze', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addIndex(['adresa'], ['name' => 'ux_popupy_adresa', 'unique' => true])
            ->create();

        $this->table('kolekce', ['id' => false, 'primary_key' => ['idk']])
            ->addColumn('idk', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 110, 'null' => false])
            ->addColumn('pole', 'text', ['null' => false])
            ->addColumn('detail', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('hidden_redirect', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'where the page of a hidden or deleted item redirects (2.10); empty = 404'])
            ->addColumn('preset', 'string', ['limit' => 30, 'null' => false, 'default' => '', 'comment' => 'the ready-made collection it was created from (2.11, Builder\\Presets); empty = its own'])
            ->addColumn('schema_org', 'text', ['null' => true, 'comment' => 'structured data of item pages: {"typ": "Service|Person|Product|Event|FAQPage", "pole": {property: field key}} (1.9)'])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addIndex(['seo_link'], ['name' => 'ux_kolekce_seo', 'unique' => true])
            ->create();

        $this->table('kolekce_polozky', ['id' => false, 'primary_key' => ['idp']])
            ->addColumn('idp', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idk', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 200, 'null' => false])
            ->addColumn('seo_link', 'string', ['limit' => 160, 'null' => false])
            ->addColumn('data', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('seo_titulek', 'string', ['limit' => 200, 'null' => false, 'default' => '', 'comment' => 'custom <title>, empty = the name (1.9)'])
            ->addColumn('popis', 'string', ['limit' => 300, 'null' => false, 'default' => '', 'comment' => 'meta description, empty = from the first text field'])
            ->addColumn('obrazek', 'string', ['limit' => 255, 'null' => false, 'default' => '', 'comment' => 'image for sharing (og:image), empty = the first image field'])
            ->addColumn('noindex', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('poradi', 'integer', ['signed' => true, 'null' => false, 'default' => 100])
            ->addColumn('zobrazit', 'boolean', ['null' => false, 'default' => 1])
            ->addColumn('zverejnit_od', 'datetime', ['null' => true, 'comment' => 'a hidden item publishes itself at this moment'])
            ->addColumn('valid_until', 'date', ['null' => true, 'comment' => 'true until: the day after, the item hides itself (2.10, Core\\Validity)'])
            ->addColumn('review_by', 'date', ['null' => true, 'comment' => 'review by: on this day the site audit asks for a check (2.10)'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => ''])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addColumn('links_checked', 'datetime', ['null' => true, 'comment' => 'when the links in the item\'s fields were last checked (2.14, Core\\Links)'])
            ->addColumn('smazano', 'datetime', ['null' => true, 'comment' => 'in the trash since (deleted permanently after 30 days); NULL = not in the trash'])
            ->addIndex(['idk', 'jazyk', 'seo_link'], ['name' => 'ux_kolekce_polozky_seo', 'unique' => true])
            ->addIndex(['idk', 'zobrazit', 'poradi'], ['name' => 'ix_kolekce_polozky'])
            ->addIndex(['zverejnit_od'], ['name' => 'ix_kolekce_polozky_zverejnit'])
            ->addForeignKey('idk', 'kolekce', 'idk', ['constraint' => $prefix . 'fk_kolekce_polozky', 'delete' => 'CASCADE'])
            ->create();

        $this->table('kolekce_sablony', ['id' => false, 'primary_key' => ['idk', 'jazyk']])
            ->addColumn('idk', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false])
            ->addColumn('stavba', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('stavba_koncept', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => true])
            ->addColumn('zmeneno', 'datetime', ['null' => true])
            ->addForeignKey('idk', 'kolekce', 'idk', ['constraint' => $prefix . 'fk_kolekce_sablony', 'delete' => 'CASCADE'])
            ->create();

        $this->table('document_versions', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idp', 'integer', ['signed' => false, 'null' => false, 'comment' => 'the document (ka_kolekce_polozky)'])
            ->addColumn('file', 'string', ['limit' => 500, 'null' => false, 'comment' => 'the replaced file: a path in Media or an https address'])
            ->addColumn('version', 'string', ['limit' => 100, 'null' => false, 'default' => '', 'comment' => 'the version number the document stated at the time'])
            ->addColumn('replaced_at', 'datetime', ['null' => false])
            ->addColumn('replaced_by', 'string', ['limit' => 100, 'null' => false, 'default' => '', 'comment' => 'who replaced it (user name, "(Claude)" over MCP)'])
            ->addIndex(['idp', 'id'], ['name' => 'ix_document_versions_item'])
            ->addForeignKey('idp', 'kolekce_polozky', 'idp', ['constraint' => $prefix . 'fk_document_versions_item', 'delete' => 'CASCADE'])
            ->create();

        $this->table('document_downloads', ['id' => false, 'primary_key' => ['idp', 'day']])
            ->addColumn('idp', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('day', 'date', ['null' => false])
            ->addColumn('count', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addForeignKey('idp', 'kolekce_polozky', 'idp', ['constraint' => $prefix . 'fk_document_downloads_item', 'delete' => 'CASCADE'])
            ->create();

        $this->table('look_versions', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('data', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false, 'comment' => '{design_system, classes: {name: {styl, css}}, menus: {"location|language": items}}'])
            ->addColumn('summary', 'string', ['limit' => 500, 'null' => false, 'default' => '', 'comment' => 'what the publishing changed, in words'])
            ->addColumn('author', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('created', 'datetime', ['null' => false])
            ->create();

        $this->table('blueprints', ['id' => false, 'primary_key' => ['bkey']])
            ->addColumn('bkey', 'string', ['limit' => 40, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false, 'default' => ''])
            ->addColumn('manifest', 'text', ['limit' => MysqlAdapter::TEXT_MEDIUM, 'null' => false])
            ->addColumn('applied_at', 'datetime', ['null' => false])
            ->create();

    }
}
