<?php

declare(strict_types=1);

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/** Generated by tools/schema-to-phinx.php from system/sql/schema.sql. */
final class CreateMediaTables extends AbstractMigration
{
    public function change(): void
    {
        $prefix = (string) $this->getAdapter()->getOption('table_prefix'); // foreign key names are unique per database

        $this->table('media_slozky', ['id' => false, 'primary_key' => ['ids']])
            ->addColumn('ids', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->create();

        $this->table('media', ['id' => false, 'primary_key' => ['ido']])
            ->addColumn('ido', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('vlastnik', 'integer', ['signed' => false, 'null' => true])
            ->addColumn('sekce', 'integer', ['signed' => false, 'null' => true, 'comment' => 'folder'])
            ->addColumn('nazev', 'string', ['limit' => 150, 'null' => false, 'default' => '', 'comment' => 'also serves as the alternative text (alt)'])
            ->addColumn('popis', 'string', ['limit' => 500, 'null' => false, 'default' => '', 'comment' => 'caption below the image'])
            ->addColumn('autor', 'string', ['limit' => 120, 'null' => false, 'default' => '', 'comment' => 'photo author (shown with the article\'s featured photo)'])
            ->addColumn('obr_poloha', 'string', ['limit' => 255, 'null' => false, 'comment' => 'path from the web root: media/2026/09/foto.jpg'])
            ->addColumn('obr_width', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('obr_height', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('obr_vel', 'integer', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'file size in bytes'])
            ->addColumn('nahl_poloha', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addColumn('nahl_width', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('nahl_height', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('barva', 'char', ['limit' => 7, 'null' => false, 'default' => '', 'comment' => 'dominant color (#rrggbb) as a placeholder before loading; \'\' = not computed, \'-\' = cannot be determined'])
            ->addColumn('ohnisko', 'string', ['limit' => 12, 'null' => false, 'default' => '', 'comment' => 'crop center (object-position), e.g. „50% 30%“; \'\' = center'])
            ->addColumn('datum', 'datetime', ['null' => false])
            ->addIndex(['datum'], ['name' => 'ix_imggal_datum'])
            ->addIndex(['obr_poloha'], ['name' => 'ix_imggal_poloha'])
            ->addIndex(['sekce'], ['name' => 'ix_imggal_sekce'])
            ->addForeignKey('sekce', 'media_slozky', 'ids', ['constraint' => $prefix . 'fk_imggal_sekce', 'delete' => 'SET_NULL'])
            ->addForeignKey('vlastnik', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_imggal_vlastnik', 'delete' => 'SET_NULL'])
            ->create();

        $this->table('media_pouziti', ['id' => false, 'primary_key' => ['ido', 'idc']])
            ->addColumn('ido', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('idc', 'integer', ['signed' => false, 'null' => false])
            ->addIndex(['idc'], ['name' => 'ix_pouziti_clanek'])
            ->addForeignKey('ido', 'media', 'ido', ['constraint' => $prefix . 'fk_pouziti_obr', 'delete' => 'CASCADE'])
            ->addForeignKey('idc', 'novinky', 'idc', ['constraint' => $prefix . 'fk_pouziti_clanek', 'delete' => 'CASCADE'])
            ->create();

    }
}
