<?php

declare(strict_types=1);

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/** Generated by tools/schema-to-phinx.php from system/sql/schema.sql. */
final class CreateIdentityTables extends AbstractMigration
{
    public function change(): void
    {
        $prefix = (string) $this->getAdapter()->getOption('table_prefix'); // foreign key names are unique per database

        $this->table('role', ['id' => false, 'primary_key' => ['idr']])
            ->addColumn('idr', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 60, 'null' => false])
            ->addColumn('popis', 'string', ['limit' => 200, 'null' => false, 'default' => ''])
            ->addColumn('uroven', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('moduly', 'string', ['limit' => 1000, 'null' => false, 'default' => '', 'comment' => 'comma-separated section identifiers'])
            ->addIndex(['nazev'], ['name' => 'uq_role_nazev', 'unique' => true])
            ->create();

        $this->table('uzivatele', ['id' => false, 'primary_key' => ['idu']])
            ->addColumn('idu', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('user', 'string', ['limit' => 40, 'null' => false, 'comment' => 'sign-in name'])
            ->addColumn('password', 'string', ['limit' => 255, 'null' => false, 'comment' => 'password_hash()'])
            ->addColumn('jmeno', 'string', ['limit' => 100, 'null' => false, 'default' => ''])
            ->addColumn('email', 'string', ['limit' => 190, 'null' => false, 'default' => ''])
            ->addColumn('url', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addColumn('admin', 'tinyinteger', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'role: 0 author, 1 editor, 2 administrator'])
            ->addColumn('role', 'integer', ['signed' => false, 'null' => true, 'comment' => 'custom role (ka_role); NULL = only the level from admin'])
            ->addColumn('blokovat', 'boolean', ['null' => false, 'default' => 0])
            ->addColumn('blokovano_automaticky', 'datetime', ['null' => true, 'comment' => 'when the automatic suspension blocked the account (Core\\SecurityHygiene); NULL = not by it'])
            ->addColumn('pocet_chyb', 'smallinteger', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'failed sign-ins in a row'])
            ->addColumn('zamceno_do', 'datetime', ['null' => true, 'comment' => 'temporary lock after 10 failed sign-ins'])
            ->addColumn('obnova_otisk', 'char', ['limit' => 64, 'null' => false, 'default' => '', 'comment' => 'sha256 of the one-time token for a password reset by e-mail; empty = nothing pending'])
            ->addColumn('obnova_cas', 'datetime', ['null' => true, 'comment' => 'when the password reset link was sent (valid for an hour)'])
            ->addColumn('totp_tajemstvi', 'string', ['limit' => 64, 'null' => false, 'default' => '', 'comment' => 'two-factor sign-in (TOTP); empty = off'])
            ->addColumn('totp_zalozni', 'text', ['null' => true, 'comment' => 'JSON: hashes of one-time backup codes'])
            ->addColumn('posledni_login', 'datetime', ['null' => true, 'comment' => 'last completed sign-in to the administration'])
            ->addColumn('potvrzeno', 'datetime', ['null' => true, 'comment' => 'created or last confirmed by an administrator (saved in Users, reactivated) – the unused-account check counts from it'])
            ->addColumn('jazyk', 'char', ['limit' => 2, 'null' => false, 'default' => '', 'comment' => 'admin language; \'\' = Czech'])
            ->addColumn('register', 'string', ['limit' => 10, 'null' => false, 'default' => '', 'comment' => 'form of address in the German administration: \'\' = formal (Sie), \'informal\' = du'])
            ->addColumn('pozice', 'string', ['limit' => 100, 'null' => false, 'default' => '', 'comment' => 'position in the company (bio of the news author)'])
            ->addColumn('foto', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addColumn('bio', 'text', ['null' => true, 'comment' => 'a few sentences about the author'])
            ->addIndex(['user'], ['name' => 'uq_user', 'unique' => true])
            ->create();

        $this->table('uzivatele_prava', ['id' => false, 'primary_key' => ['fk_id_user', 'ident_modulu']])
            ->addColumn('fk_id_user', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('ident_modulu', 'string', ['limit' => 30, 'null' => false])
            ->addForeignKey('fk_id_user', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_prava_user', 'delete' => 'CASCADE'])
            ->create();

        $this->table('uzivatele_klice', ['id' => false, 'primary_key' => ['idk']])
            ->addColumn('idk', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idu', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 80, 'null' => false, 'default' => '', 'comment' => 'the device name given by the user („MacBook“, „telefon“)'])
            ->addColumn('otisk_id', 'char', ['limit' => 64, 'null' => false, 'comment' => 'sha256 of the key identifier (the identifier can be up to 1023 bytes)'])
            ->addColumn('id_klice', 'text', ['null' => false, 'comment' => 'key identifier, base64url'])
            ->addColumn('verejny', 'text', ['null' => false, 'comment' => 'the device\'s public key (PEM)'])
            ->addColumn('alg', 'smallinteger', ['signed' => true, 'null' => false, 'comment' => 'signature algorithm per COSE: -7 ES256, -257 RS256'])
            ->addColumn('pocitadlo', 'integer', ['signed' => false, 'null' => false, 'default' => 0, 'comment' => 'signature counter; if the device keeps one, it must increase'])
            ->addColumn('vytvoreno', 'datetime', ['null' => false])
            ->addColumn('pouzito', 'datetime', ['null' => true])
            ->addIndex(['otisk_id'], ['name' => 'uq_klice_otisk', 'unique' => true])
            ->addIndex(['idu'], ['name' => 'ix_klice_user'])
            ->addForeignKey('idu', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_klice_user', 'delete' => 'CASCADE'])
            ->create();

        $this->table('api_tokeny', ['id' => false, 'primary_key' => ['idt']])
            ->addColumn('idt', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('idu', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false])
            ->addColumn('klient', 'char', ['limit' => 32, 'null' => true, 'comment' => 'OAuth client_id; NULL = a personal token from "Můj účet" (My account)'])
            ->addColumn('druh', 'string', ['limit' => 10, 'null' => false, 'default' => 'token', 'comment' => 'token | pristup | obnova'])
            ->addColumn('access', 'string', ['limit' => 10, 'null' => false, 'default' => 'full', 'comment' => 'full | drafts | read – what the connection may do (2.2)'])
            ->addColumn('expirace', 'datetime', ['null' => true])
            ->addColumn('otisk', 'char', ['limit' => 64, 'null' => false, 'comment' => 'sha256 of the token'])
            ->addColumn('vytvoren', 'datetime', ['null' => false])
            ->addColumn('pouzit', 'datetime', ['null' => true])
            ->addIndex(['otisk'], ['name' => 'uq_tokeny_otisk', 'unique' => true])
            ->addIndex(['klient'], ['name' => 'ix_tokeny_klient'])
            ->addForeignKey('idu', 'uzivatele', 'idu', ['constraint' => $prefix . 'fk_tokeny_user', 'delete' => 'CASCADE'])
            ->create();

        $this->table('oauth_klienti', ['id' => false, 'primary_key' => ['idk']])
            ->addColumn('idk', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('client_id', 'char', ['limit' => 32, 'null' => false])
            ->addColumn('tajemstvi', 'char', ['limit' => 64, 'null' => false, 'default' => '', 'comment' => 'sha256 client_secret; empty = public client (PKCE only)'])
            ->addColumn('nazev', 'string', ['limit' => 100, 'null' => false, 'default' => ''])
            ->addColumn('presmerovani', 'text', ['null' => false, 'comment' => 'JSON list of allowed redirect_uri'])
            ->addColumn('vytvoren', 'datetime', ['null' => false])
            ->addIndex(['client_id'], ['name' => 'uq_oauth_klient', 'unique' => true])
            ->create();

        $this->table('oauth_kody', ['id' => false, 'primary_key' => ['otisk']])
            ->addColumn('otisk', 'char', ['limit' => 64, 'null' => false, 'comment' => 'sha256 of the code'])
            ->addColumn('client_id', 'char', ['limit' => 32, 'null' => false])
            ->addColumn('idu', 'integer', ['signed' => false, 'null' => false])
            ->addColumn('presmerovani', 'string', ['limit' => 500, 'null' => false])
            ->addColumn('vyzva', 'string', ['limit' => 128, 'null' => false, 'comment' => 'code_challenge (PKCE, S256)'])
            ->addColumn('access', 'string', ['limit' => 10, 'null' => false, 'default' => 'full', 'comment' => 'the access chosen on the consent screen'])
            ->addColumn('expirace', 'datetime', ['null' => false])
            ->create();

        $this->table('kontrola_ip', ['id' => false, 'primary_key' => ['idk']])
            ->addColumn('idk', 'integer', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('ip_adresa', 'string', ['limit' => 45, 'null' => false])
            ->addColumn('typ', 'string', ['limit' => 20, 'null' => false])
            ->addColumn('cil', 'integer', ['signed' => false, 'null' => false, 'default' => 0])
            ->addColumn('cas', 'datetime', ['null' => false])
            ->addIndex(['typ', 'cil', 'ip_adresa', 'cas'], ['name' => 'ix_kontrola'])
            ->create();

        $this->table('firewall_blocks', ['id' => false, 'primary_key' => ['ip']])
            ->addColumn('ip', 'string', ['limit' => 45, 'null' => false])
            ->addColumn('until', 'datetime', ['null' => false])
            ->addColumn('reason', 'string', ['limit' => 40, 'null' => false, 'default' => ''])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addIndex(['until'], ['name' => 'ix_firewall_blocks_until'])
            ->create();

        $this->table('firewall_log', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['signed' => false, 'identity' => true, 'null' => false])
            ->addColumn('created_at', 'datetime', ['null' => false])
            ->addColumn('ip', 'string', ['limit' => 45, 'null' => false])
            ->addColumn('reason', 'string', ['limit' => 40, 'null' => false, 'comment' => 'list | country | rate | probe | temporary'])
            ->addColumn('path', 'string', ['limit' => 255, 'null' => false, 'default' => ''])
            ->addIndex(['created_at'], ['name' => 'ix_firewall_log_created'])
            ->create();

    }
}
